name: social_media_downloader
description: Simple downloader client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  open_file: ^3.2.1

flutter:
  uses-material-design: true